on:
  release:
    types: [released]
jobs:
  test:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Ref Names
        id: ref_names
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Debug Ref Names
        run: |
          echo $SOURCE_NAME
          echo $SOURCE_BRANCH
          echo $SOURCE_TAG
        env:
          SOURCE_NAME: ${{ steps.ref_names.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.ref_names.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.ref_names.outputs.SOURCE_TAG }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'tph'
      - name: Configure
        run: |
          cmake -B tph/BUILD \
            -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=tph/INSTALL \
            -DBUILD_TESTING=TRUE \
            tph
      - name: Build 
        run: cmake --build tph/BUILD --target install 
      - name: Create Artefacts
        run: tar -zcvf tph-${SOURCE_TAG}.tar.gz tph/INSTALL
        env:
          SOURCE_TAG: ${{ steps.ref_names.outputs.SOURCE_TAG }}
#      - name: Version up
#        run: |
#          git config --global user.name 'Nihil Nomen'
#          git config --global user.email 'nn@gmail.com'
#          rm VERSION.txt
#          echo ${SOURCE_TAG} > VERSION.txt
#          git commit -am "Automated Version Up: ${SOURCE_TAG}"
#          git tag ${SOURCE_TAG} -f
#          git push origin HEAD:master
#          git push -f origin ${SOURCE_TAG}
#        env:
#          SOURCE_TAG: ${{ steps.ref_names.outputs.SOURCE_TAG }}
      - name: Upload Artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'tph-*.tar.gz'