on:
  release:
    types: [released]
jobs:
  test:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ref Names
        id: ref_names
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Debug Ref Names
        run: |
          echo $SOURCE_NAME
          echo $SOURCE_BRANCH
          echo $SOURCE_TAG
        env:
          SOURCE_NAME: ${{ steps.ref_names.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.ref_names.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.ref_names.outputs.SOURCE_TAG }}
      - name: Version up
        run: |
          git config --global user.name 'Git Pirate'
          git config --global user.email 'tech@ilpvfx.com'
          sed -i -E "s/(\s+\"version\":)(.*,)/\1 \"${SOURCE_TAG}\",/g" package.json
          git commit -am "Automated Version Up: ${SOURCE_TAG}"
          git tag ${SOURCE_TAG} -f
          git push origin HEAD:master
          git push -f origin ${SOURCE_TAG}
        env:
          SOURCE_TAG: ${{ steps.ref_names.outputs.SOURCE_TAG }}
#      - name: Upload the artifacts
#        uses: skx/github-action-publish-binaries@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          args: 'rez-dev-env-*.vsix'